[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hashtrace"
version = "1.0.1"
description = "Forensic file integrity engine & cryptographic hash generator"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Shraddha", email = "urstrulyshraddha07@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Security :: Cryptography",
    "Environment :: Console",
]

[project.scripts]
hashtrace = "hashtrace.cli:main"
hace = "hashtrace.cli:main"

[project.urls]
Homepage = "https://github.com/urstrulyshraddha/HashTrace"
Issues = "https://github.com/urstrulyshraddha/HashTrace/issues"
